// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9MRazEE2RcaEv6Njh43p2r31UlV_xCHc',
    appId: '1:531785642546:web:ba1abee4461702ac3f822b',
    messagingSenderId: '531785642546',
    projectId: 'pbl-reader',
    authDomain: 'pbl-reader.firebaseapp.com',
    storageBucket: 'pbl-reader.firebasestorage.app',
    measurementId: 'G-QRE0Q8WMV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDohsv2sD7k7ycxhSF2xQq3F40FHak0IQs',
    appId: '1:531785642546:android:751b76cf67d2b33f3f822b',
    messagingSenderId: '531785642546',
    projectId: 'pbl-reader',
    storageBucket: 'pbl-reader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJt0OweKXedgpQ_Ok_5gPeKhyD0GNsnc',
    appId: '1:531785642546:ios:79f95fea57dbec2f3f822b',
    messagingSenderId: '531785642546',
    projectId: 'pbl-reader',
    storageBucket: 'pbl-reader.firebasestorage.app',
    iosBundleId: 'com.example.pblReaderEra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJt0OweKXedgpQ_Ok_5gPeKhyD0GNsnc',
    appId: '1:531785642546:ios:79f95fea57dbec2f3f822b',
    messagingSenderId: '531785642546',
    projectId: 'pbl-reader',
    storageBucket: 'pbl-reader.firebasestorage.app',
    iosBundleId: 'com.example.pblReaderEra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9MRazEE2RcaEv6Njh43p2r31UlV_xCHc',
    appId: '1:531785642546:web:63a4b7e2dcd4bfc23f822b',
    messagingSenderId: '531785642546',
    projectId: 'pbl-reader',
    authDomain: 'pbl-reader.firebaseapp.com',
    storageBucket: 'pbl-reader.firebasestorage.app',
    measurementId: 'G-DH2DTRY54N',
  );

}